export const LOADING = "LOADING"
export const GETALLPRODUCTSUCCES = "GETALLPRODUCTSUCCES"
export const GETALLPRODUCTFAILED = "GETALLPRODUCTFAILED"

export const GETONEPRODUCTSUCCES = "GETONEPRODUCTSUCCES"
export const GETONEPRODUCTFAILED = "GETONEPRODUCTFAILED"

export const ADDPRODUCTSUCCES = "ADDPRODUCTSUCCES"
export const ADDPRODUCTFAILED = "ADDPRODUCTFAILED"